# Generated by Django 5.1.3 on 2024-11-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0009_remove_missingperson_missing_per_missing_c4a9fd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='missingperson',
            name='Missing_per_missing_37673c_idx',
        ),
        migrations.RenameField(
            model_name='missingperson',
            old_name='location',
            new_name='Missing_location',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='longitude',
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['missing_time', 'missing_date', 'Missing_location'], name='Missing_per_missing_30a9ae_idx'),
        ),
    ]
