# Generated by Django 5.1.3 on 2024-11-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0010_remove_missingperson_missing_per_missing_37673c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='missingperson',
            name='Missing_per_missing_30a9ae_idx',
        ),
        migrations.RenameField(
            model_name='missingperson',
            old_name='Missing_location',
            new_name='missing_location',
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['missing_time', 'missing_date', 'missing_location'], name='Missing_per_missing_fa6d80_idx'),
        ),
    ]
