# Generated by Django 5.1.3 on 2024-11-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0012_remove_address_latitude_remove_address_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='condition',
            field=models.CharField(blank=True, choices=[('Memory loss', 'Memory loss'), ('Shock', 'Shock'), ('Anxiety', 'Anxiety'), ('Depression', 'Depression'), ('Fatigue', 'Fatigue'), ('Headache', 'Headache'), ('Dizziness', 'Dizziness'), ('Nausea', 'Nausea'), ('Chest pain', 'Chest pain'), ('Shortness of breath', 'Shortness of breath'), ('Confusion', 'Confusion'), ('Hallucinations', 'Hallucinations'), ('Severe pain', 'Severe pain'), ('Paralysis', 'Paralysis')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='identification_details',
            field=models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('Pan Card', 'Pan Card'), ('Driving License', 'Driving License'), ('Passport', 'Passport'), ('VoterID', 'VoterID')], db_index=True, max_length=50),
        ),
    ]
