# Generated by Django 5.1.3 on 2024-11-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0013_match_is_confirmed_alter_missingperson_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_percentage', models.FloatField()),
                ('rejection_reason', models.TextField()),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Missing_persons.missingperson')),
                ('undefined_missing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Missing_persons.unidentifiedmissingperson')),
                ('unidentified_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Missing_persons.unidentifiedbody')),
            ],
        ),
    ]
