# Generated by Django 5.1.3 on 2024-11-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0015_matchrejection_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrejection',
            name='rejection_percentage',
            field=models.FloatField(default=0),
        ),
    ]
