# Generated by Django 5.1.3 on 2024-11-18 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0020_missingperson_rematch_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='matchrejection',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='matchrejection',
            name='rejection_percentage',
        ),
        migrations.AddField(
            model_name='matchrejection',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Missing_persons.match'),
        ),
    ]
