# Generated by Django 5.1.3 on 2024-11-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0021_remove_match_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrejection',
            name='matched_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
