# Generated by Django 5.1.3 on 2024-11-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0022_matchrejection_matched_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
