# Generated by Django 5.1.3 on 2024-11-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0026_alter_match_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrejection',
            name='MATCH_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
