# Generated by Django 5.1.3 on 2024-11-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0027_matchrejection_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedcase',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Missing_persons.match'),
        ),
    ]
