# Generated by Django 5.1.3 on 2024-11-18 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0028_resolvedcase_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Missing_persons.match'),
        ),
    ]
