# Generated by Django 5.1.3 on 2024-11-18 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0030_remove_casereport_missing_per_report__210a20_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviouslyMatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('matched_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_matches', to='Missing_persons.missingperson')),
                ('undefined_missing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_missing_persons', to='Missing_persons.unidentifiedmissingperson')),
                ('unidentified_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_missing_persons', to='Missing_persons.unidentifiedbody')),
            ],
            options={
                'unique_together': {('missing_person', 'undefined_missing_person', 'unidentified_body')},
            },
        ),
    ]
