# Generated by Django 5.1.3 on 2024-11-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0031_previouslymatched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casereport',
            name='match',
        ),
    ]
