# Generated by Django 3.2 on 2024-11-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0032_remove_casereport_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='address',
            new_name='hospital_address',
        ),
    ]
