# Generated by Django 3.2 on 2024-11-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0034_auto_20241122_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedbody',
            name='Volunteers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidentified_bodies', to='Missing_persons.volunteer'),
        ),
    ]
