# Generated by Django 5.1.3 on 2024-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0038_alter_address_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='landmark',
            new_name='landmark_details',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('United States of America', 'United States of America'), ('China', 'China'), ('Japan', 'Japan'), ('Germany', 'Germany'), ('United Kingdom', 'United Kingdom'), ('France', 'France'), ('Brazil', 'Brazil'), ('Australia', 'Australia'), ('Canada', 'Canada')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='subtype',
            field=models.CharField(choices=[('Permanent Address', 'Permanent Address'), ('Current Address', 'Current Address'), ('Emergency', 'Emergency'), ('Current', 'Current'), ('Person Founded', 'Person Founded'), ('Body Founded', 'Body Founded')], db_index=True, max_length=50),
        ),
    ]
