# Generated by Django 5.1.3 on 2024-12-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0040_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='Age',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
