# Generated by Django 5.1.3 on 2024-12-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0042_remove_volunteer_missing_per_full_na_934fc2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chowki',
            name='location',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='location',
        ),
    ]
