# Generated by Django 5.1.3 on 2024-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0043_remove_chowki_location_remove_policestation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='chowki',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='ALLphotos/police-chowkis/', verbose_name='Photo Upload'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='ALLphotos/Hospitals/', verbose_name='Photo Upload'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='ALLphotos/police-station/', verbose_name='Photo Upload'),
        ),
    ]
