# Generated by Django 5.1.3 on 2024-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0047_hospital_telephone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='telephone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
