# Generated by Django 5.1.3 on 2024-12-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0049_unidentifiedmissingperson_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidentifiedmissingperson',
            name='blood_Group',
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=50, null=True, verbose_name='blood_group'),
        ),
    ]
