# Generated by Django 5.1.3 on 2024-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0050_remove_unidentifiedmissingperson_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedbody',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=50, null=True, verbose_name='Marital Status'),
        ),
    ]
