# Generated by Django 5.1.3 on 2024-12-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0051_unidentifiedbody_marital_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unidentifiedbody',
            name='Missing_per_birth_m_eb1a9b_idx',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='case_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Reopened', 'Reopened'), ('Pending', 'Pending')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='case_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Not Identified', 'Not Identified'), ('Unsolved', 'Unsolved'), ('Reopened', 'Reopened'), ('Pending', 'Pending')], db_index=True, default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='condition',
            field=models.CharField(blank=True, choices=[('Decomposed', 'Decomposed'), ('Intact', 'Intact'), ('Mummified', 'Mummified'), ('Skeletonized', 'Skeletonized'), ('Partially Decayed', 'Partially Decayed'), ('Emaciated', 'Emaciated'), ('Burnt', 'Burnt'), ('Traumatic Injury', 'Traumatic Injury'), ('Fresh', 'Fresh')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='case_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Not Identified', 'Not Identified'), ('Unsolved', 'Unsolved'), ('Reopened', 'Reopened'), ('Pending', 'Pending')], db_index=True, default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='condition',
            field=models.CharField(blank=True, choices=[('Memory loss', 'Memory loss'), ('Shock', 'Shock'), ('Anxiety', 'Anxiety'), ('Depression', 'Depression'), ('Fatigue', 'Fatigue'), ('Headache', 'Headache'), ('Dizziness', 'Dizziness'), ('Nausea', 'Nausea'), ('Chest pain', 'Chest pain'), ('Shortness of breath', 'Shortness of breath'), ('Confusion', 'Confusion'), ('Hallucinations', 'Hallucinations'), ('Severe pain', 'Severe pain'), ('Paralysis', 'Paralysis')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='unidentifiedbody',
            index=models.Index(fields=['birth_mark', 'other_distinctive_mark', 'condition', 'blood_group'], name='Missing_per_birth_m_da659f_idx'),
        ),
    ]
