# Generated by Django 5.1.3 on 2024-12-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0052_remove_unidentifiedbody_missing_per_birth_m_eb1a9b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='missingperson',
            name='Missing_per_full_na_c2697c_idx',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='unique_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['unique_id', 'full_name', 'age', 'date_of_birth', 'gender', 'time_of_birth', 'place_of_birth'], name='Missing_per_unique__99c3cb_idx'),
        ),
    ]
