# Generated by Django 5.1.3 on 2024-12-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0053_remove_missingperson_missing_per_full_na_c2697c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedbody',
            name='unique_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='unique_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='case_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Reopened', 'Reopened'), ('Pending', 'Pending'), ('Found Alive', 'Found Alive'), ('Deceased', 'Deceased')], default='Open', max_length=20),
        ),
    ]
