# Generated by Django 5.1.3 on 2024-12-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0055_bodymatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolvedcase',
            name='confirmed_by',
        ),
        migrations.AddField(
            model_name='resolvedcase',
            name='confirmed_by_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resolvedcase',
            name='confirmed_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resolvedcase',
            name='confirmed_by_relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resolvedcase',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
