# Generated by Django 5.1.3 on 2024-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0056_remove_resolvedcase_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedcase',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
