# Generated by Django 5.1.3 on 2024-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0057_resolvedcase_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
