# Generated by Django 5.1.3 on 2024-12-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0062_alter_unidentifiedbody_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidentifiedbody',
            name='case_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Found Alive', 'Found Alive'), ('Found_Alive_With_Unidentified', 'Found_Alive_With_Unidentified')], db_index=True, default='Pending', max_length=50),
        ),
    ]
