# Generated by Django 5.1.3 on 2025-01-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0063_alter_unidentifiedbody_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unidentifiedbody',
            name='case_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Found Alive_with_missing', 'Found Alive_with_missing'), ('Found_Alive_With_Unidentified', 'Found_Alive_With_Unidentified')], db_index=True, default='Pending', max_length=50),
        ),
    ]
