# Generated by Django 5.1.3 on 2025-02-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0064_missingperson_consent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='Missing_per_locatio_0f5d0d_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
    ]
