# Generated by Django 5.1.3 on 2025-02-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0065_remove_contact_missing_per_locatio_0f5d0d_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='missingperson',
            new_name='Missing_per_police__bbe694_idx',
            old_name='Missing_per_police__ea404d_idx',
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='police_station_name_and_address',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
