# Generated by Django 5.1.3 on 2025-02-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0066_rename_missing_per_police__ea404d_idx_missing_per_police__bbe694_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='subtype',
            field=models.CharField(choices=[('Permanent Address', 'Permanent Address'), ('Current Address', 'Current Address'), ('Emergency', 'Emergency'), ('Person Founded', 'Person Founded'), ('Body Founded', 'Body Founded')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], db_index=True, max_length=20),
        ),
    ]
