# Generated by Django 5.1.3 on 2025-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0067_alter_address_subtype_alter_missingperson_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chowki',
            name='police_station_name_and_address',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
