# Generated by Django 5.1.3 on 2025-02-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0068_chowki_police_station_name_and_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='identification_card_no',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
