# Generated by Django 5.1.3 on 2025-02-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0069_alter_missingperson_identification_card_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subtype_detail',
        ),
    ]
