# Generated by Django 5.1.3 on 2025-02-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0070_remove_contact_subtype_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_person', to='Missing_persons.address'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='caste',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_person', to='Missing_persons.contact'),
        ),
    ]
