# Generated by Django 5.1.3 on 2025-02-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0071_alter_missingperson_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='identification_card_no',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
    ]
