# Generated by Django 5.1.3 on 2025-02-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0072_alter_missingperson_identification_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='age',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
