# Generated by Django 5.1.3 on 2025-02-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0073_alter_missingperson_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='fir_photo',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to=''),
        ),
    ]
