# Generated by Django 5.1.3 on 2025-02-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0075_alter_missingperson_fir_photo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='missingperson',
            name='Missing_per_address_a94126_idx',
        ),
        migrations.RemoveIndex(
            model_name='unidentifiedbody',
            name='Missing_per_address_c03a33_idx',
        ),
        migrations.RemoveIndex(
            model_name='unidentifiedmissingperson',
            name='Missing_per_address_3c4a47_idx',
        ),
        migrations.RemoveIndex(
            model_name='volunteer',
            name='Missing_per_address_715daf_idx',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='address',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='unidentifiedbody',
            name='address',
        ),
        migrations.RemoveField(
            model_name='unidentifiedbody',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='unidentifiedmissingperson',
            name='address',
        ),
        migrations.RemoveField(
            model_name='unidentifiedmissingperson',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='contact',
        ),
        migrations.AddField(
            model_name='address',
            name='Unidentified_Body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Missing_persons.unidentifiedbody'),
        ),
        migrations.AddField(
            model_name='address',
            name='Unidentified_MissingPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Missing_persons.unidentifiedmissingperson'),
        ),
        migrations.AddField(
            model_name='address',
            name='Volunteers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Missing_persons.volunteer'),
        ),
        migrations.AddField(
            model_name='address',
            name='missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Missing_persons.missingperson'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Unidentified_Body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Missing_persons.unidentifiedbody'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Unidentified_MissingPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Missing_persons.unidentifiedmissingperson'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Volunteers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Missing_persons.volunteer'),
        ),
        migrations.AddField(
            model_name='contact',
            name='missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Missing_persons.missingperson'),
        ),
        migrations.RemoveField(
            model_name='unidentifiedbody',
            name='Volunteers',
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['condition'], name='Missing_per_conditi_2c94df_idx'),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='Volunteers',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='unidentified_bodies', to='Missing_persons.volunteer'),
        ),
    ]
