# Generated by Django 5.1.3 on 2025-02-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0076_remove_missingperson_missing_per_address_a94126_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='missingperson',
            name='Missing_per_conditi_2c94df_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Unidentified_Body',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Unidentified_MissingPerson',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Volunteers',
        ),
        migrations.RemoveField(
            model_name='address',
            name='missing_person',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Unidentified_Body',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Unidentified_MissingPerson',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Volunteers',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='missing_person',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_person', to='Missing_persons.address'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_person', to='Missing_persons.contact'),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidentified_bodies', to='Missing_persons.address'),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidentified_bodies', to='Missing_persons.contact'),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Undefined_missing_person', to='Missing_persons.address'),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Undefined_missing_person', to='Missing_persons.contact'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='Missing_persons.address'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='Missing_persons.contact'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='fir_photo',
            field=models.BinaryField(blank=True, db_index=True, null=True),
        ),
        migrations.RemoveField(
            model_name='unidentifiedbody',
            name='Volunteers',
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['address', 'contact', 'condition'], name='Missing_per_address_a94126_idx'),
        ),
        migrations.AddIndex(
            model_name='unidentifiedbody',
            index=models.Index(fields=['address', 'contact'], name='Missing_per_address_c03a33_idx'),
        ),
        migrations.AddIndex(
            model_name='unidentifiedmissingperson',
            index=models.Index(fields=['address', 'contact'], name='Missing_per_address_3c4a47_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['address', 'contact'], name='Missing_per_address_715daf_idx'),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='Volunteers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidentified_bodies', to='Missing_persons.volunteer'),
        ),
    ]
