# Generated by Django 5.1.3 on 2025-02-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0077_remove_missingperson_missing_per_conditi_2c94df_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedbody',
            name='relationship_with_victim',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Relationship with Victim'),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='reporting_person_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number(s)'),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='reporting_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='reporting_person_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Reporting Person'),
        ),
    ]
