# Generated by Django 5.1.3 on 2025-02-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0078_unidentifiedbody_relationship_with_victim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedbody',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
