# Generated by Django 5.1.3 on 2025-02-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0079_unidentifiedbody_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='station_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Closed', 'Closed')], default='Active', null=True),
        ),
    ]
