# Generated by Django 5.1.3 on 2024-11-11 09:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0008_casereport_hospital_pk'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='missingperson',
            name='Missing_per_missing_c4a9fd_idx',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='missingperson',
            index=models.Index(fields=['missing_time', 'missing_date', 'latitude', 'longitude', 'location'], name='Missing_per_missing_37673c_idx'),
        ),
    ]
