# Generated by Django 5.1.3 on 2024-11-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0014_matchrejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrejection',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
