# Generated by Django 5.1.3 on 2024-11-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0016_alter_matchrejection_rejection_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
