# Generated by Django 5.1.3 on 2024-11-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0017_match_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
