# Generated by Django 5.1.3 on 2024-11-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0018_match_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='resolution_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Resolved - Found Alive', 'Resolved - Found Alive'), ('Resolved - Deceased', 'Resolved - Deceased')], max_length=50, null=True),
        ),
    ]
