# Generated by Django 5.1.3 on 2024-11-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0019_alter_match_resolution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='rematch_attempt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
