# Generated by Django 5.1.3 on 2024-11-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0024_alter_match_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
