# Generated by Django 5.1.3 on 2024-11-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0029_casereport_match'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='casereport',
            name='Missing_per_report__210a20_idx',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='case_id',
        ),
        migrations.AddField(
            model_name='casereport',
            name='MATCH_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='casereport',
            index=models.Index(fields=['report_number'], name='Missing_per_report__4bc557_idx'),
        ),
    ]
