# Generated by Django 3.2 on 2024-11-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0033_rename_address_hospital_hospital_address'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unidentifiedbody',
            name='Missing_per_body_ph_4a899e_idx',
        ),
        migrations.RenameField(
            model_name='unidentifiedbody',
            old_name='last_seen_details',
            new_name='body_seen_details',
        ),
        migrations.AddIndex(
            model_name='unidentifiedbody',
            index=models.Index(fields=['body_photo_upload', 'clothing_description', 'body_seen_details'], name='Missing_per_body_ph_beedf7_idx'),
        ),
    ]
