# Generated by Django 3.2 on 2024-11-22 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0035_unidentifiedbody_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='Volunteers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Undefined_missing_person', to='Missing_persons.volunteer'),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='fir_number',
            field=models.IntegerField(blank=True, db_index=True, help_text='FIR Number assigned for the case', null=True),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='fir_photo',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to='ALLphotos/Unidnetified_missing_person/fir_photos/'),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Undefined_missing_person', to='Missing_persons.hospital'),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='investigating_officer_contact_number',
            field=models.CharField(blank=True, db_index=True, help_text='Contact number of the investigating officer', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='investigating_officer_name',
            field=models.CharField(blank=True, db_index=True, help_text='Name of the investigating police officer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='police_station_name_and_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Undefined_missing_person', to='Missing_persons.chowki'),
        ),
    ]
