# Generated by Django 5.1.3 on 2024-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0039_rename_landmark_address_landmark_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
