# Generated by Django 5.1.3 on 2024-12-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0041_volunteer_age'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='volunteer',
            name='Missing_per_full_na_934fc2_idx',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='photo_upload',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='ALLphotos/Volunteer/'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['full_name', 'dob', 'gender', 'photo_upload', 'is_active'], name='Missing_per_full_na_382bcf_idx'),
        ),
    ]
