# Generated by Django 5.1.3 on 2024-12-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0046_chowki_country_chowki_website_hospital_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='telephone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
