# Generated by Django 5.1.3 on 2024-12-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0054_unidentifiedbody_unique_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField()),
                ('match_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('match_type', models.CharField(default='Partial', max_length=50)),
                ('matching_criteria', models.JSONField(blank=True, null=True)),
                ('resolution_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Resolved - Found Alive', 'Resolved - Found Alive'), ('Resolved - Deceased', 'Resolved - Deceased')], max_length=50, null=True)),
                ('date_matched', models.DateTimeField(auto_now_add=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('missing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Missing_persons.missingperson')),
                ('undefined_missing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Missing_persons.unidentifiedmissingperson')),
                ('unidentified_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Missing_persons.unidentifiedbody')),
            ],
            options={
                'unique_together': {('unidentified_body', 'missing_person', 'undefined_missing_person', 'match_percentage', 'match_type')},
            },
        ),
    ]
