# Generated by Django 5.1.3 on 2024-12-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0058_match_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='case_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Reopened', 'Reopened'), ('Pending', 'Pending'), ('Found Alive', 'Found Alive'), ('Deceased', 'Deceased')], default='Pending', max_length=20),
        ),
    ]
