# Generated by Django 5.1.3 on 2024-12-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0059_alter_missingperson_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidentifiedbody',
            name='case_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Not Identified', 'Not Identified'), ('Unsolved', 'Unsolved'), ('Reopened', 'Reopened'), ('Pending', 'Pending')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidentifiedmissingperson',
            name='case_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Not Identified', 'Not Identified'), ('Unsolved', 'Unsolved'), ('Reopened', 'Reopened'), ('Pending', 'Pending')], db_index=True, default='Pending', max_length=20),
        ),
    ]
