# Generated by Django 5.1.3 on 2024-12-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0060_alter_unidentifiedbody_case_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidentifiedmissingperson',
            name='case_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Reopened', 'Reopened'), ('Pending', 'Pending'), ('Found Alive', 'Found Alive'), ('Deceased', 'Deceased')], db_index=True, default='Pending', max_length=20),
        ),
    ]
