import { MissingPersonForm } from "./interface";

export const dummyFormValues: MissingPersonForm = {
    full_name: "amit dake",
    gender: "Male",
    blood_group: "O+",
    date_of_birth: "2001-01-27",
    age: 24,
    time_of_birth: "01:10",
    place_of_birth: "Pune",
    height: 156,
    weight: 70,
    complexion: "Fair",
    hair_color: "Black",
    hair_type: "Straight",
    eye_color: "Amber",
    birth_mark: "Na",
    distinctive_mark: "akjsd",
    caste: "Open",
    sub_caste: "Maratha",
    marital_status: "Single",
    religion: "Hindu",
    mother_tongue: "Marathi",
    known_languages: "English",
    educational_details: "Graduate",
    occupation: "job",
    identification_details: "Aadhar Card",
    identification_card_no: "147852369857",
    missing_time: "02:16",
    missing_date: "2025-01-26",
    location_details: "NA",
    last_seen_location: "Naskjdjk",
    case_status: "Pending",
    condition: "Memory loss",
    fir_number: "147856",
    police_station_name_and_address: "bharti police station",
    investigating_officer_name: "varma",
    investigating_officer_contact_number: "1236547890",
    reportingperson_name: "sanket",
    relationship_with_victim: "Friend",
    contact_numbers: "9923666493",
    email_address: "s@gmail.com",
    consent: true,
    willing_to_volunteer: false,
    photo_upload: null,
    fir_photo: null,
    missing_location: { latitude: 18.450771, longitude: 73.853657 },
    contact: { 
        phone_number: "9923666493",
        email: "s@gmail.com", 
        type: "Missing Person", 
        subtype: "Personal", 
        is_primary: true
    },
    address: { 
        street: "123 Main St", 
        city: "Pune", 
        state: "Maharashtra", 
        postal_code: "411001", 
        country_code: "+91", 
        country: "India", 
        type: "Missing Person",
        subtype: "Permanent Address",
        location: { latitude: 18.450771, longitude: 73.853657 },
        is_active: true
    }
};