export interface MissingPersonForm {
    full_name: string;
    gender: string;
    blood_group: string;
    date_of_birth: string;
    age: number;
    time_of_birth: string;
    place_of_birth: string;
    height: number;
    weight: number;
    complexion: string;
    hair_color: string;
    hair_type: string;
    eye_color: string;
    birth_mark: string;
    distinctive_mark: string;
    caste: string;
    sub_caste: string;
    marital_status: string;
    religion: string;
    mother_tongue: string;
    known_languages: string;
    educational_details: string;
    occupation: string;
    identification_details: string;
    identification_card_no: string;
    missing_time: string;
    missing_date: string;
    location_details: string;
    last_seen_location: string;
    case_status: string;
    condition: string;
    fir_number: string;
    police_station_name_and_address: string;
    investigating_officer_name: string;
    investigating_officer_contact_number: string;
    reportingperson_name: string;
    relationship_with_victim: string;
    contact_numbers: string;
    email_address: string;
    consent: boolean;
    willing_to_volunteer: boolean;
    photo_upload: File | null;
    fir_photo: File | null;
    missing_location: { latitude: number; longitude: number };
    contact: { 
        phone_number: string;
        email: string; 
        type: string; 
        subtype: string; 
        is_primary: boolean;
    };
    address: { 
        street: string; 
        city: string; 
        state: string; 
        postal_code: string; 
        country_code: string; 
        country: string; 
        type: string;
        subtype: string;
        location: { latitude: number; longitude: number };
        is_active: boolean;
    };
}