# Generated by Django 5.1.3 on 2025-02-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country_cd',
            field=models.CharField(blank=True, db_index=True, help_text='Country Code', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.EmailField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone_no'], name='Mainapp_con_phone_n_9fee8b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email_id'], name='Mainapp_con_email_i_b9a834_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['country_cd'], name='Mainapp_con_country_69864b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['created_at'], name='Mainapp_con_created_3b2e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['updated_at'], name='Mainapp_con_updated_5e4798_idx'),
        ),
    ]
