# Generated by Django 5.1.3 on 2025-03-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='Mainapp_per_match_e_62d184_idx',
        ),
        migrations.RemoveField(
            model_name='person',
            name='match_with',
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['match_entity_id'], name='Mainapp_per_match_e_cf7d08_idx'),
        ),
    ]
