# Generated by Django 5.1.3 on 2025-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_remove_person_mainapp_per_match_e_62d184_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='match_with',
            field=models.CharField(blank=True, choices=[('Missing Person', 'Missing Person'), ('Unidentified Person', 'Unidentified Person'), ('Unidentified Body', 'Unidentified Body')], help_text='The type of the matched entity', max_length=20, null=True),
        ),
    ]
