# Generated by Django 5.1.3 on 2025-02-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_alter_contact_country_cd_alter_contact_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinfo',
            old_name='languages',
            new_name='other_known_languages',
        ),
    ]
