# Generated by Django 5.1.3 on 2025-02-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_rename_languages_additionalinfo_other_known_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastknowndetails',
            name='last_seen_location',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lastknowndetails',
            name='missing_location_details',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lastknowndetails',
            name='missing_location_place',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastknowndetails',
            name='missing_date',
            field=models.DateField(blank=True, help_text='Date the person went missing', null=True),
        ),
    ]
