# Generated by Django 5.1.3 on 2025-03-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_person_match_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='match_with',
            field=models.CharField(blank=True, choices=[('Missing Person', 'missing person'), ('Unidentified Person', 'unidentified person'), ('Unidentified Body', 'unidentified body')], help_text='The type of the matched entity', max_length=20, null=True),
        ),
    ]
