# Generated by Django 5.1.3 on 2025-03-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_alter_person_match_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_with',
            field=models.CharField(blank=True, choices=[('Missing Person', 'missing person'), ('Unidentified Person', 'unidentified person'), ('Unidentified Body', 'unidentified body')], help_text='The type of the matched entity', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Matched', 'matched')], default='Matched', max_length=10),
        ),
    ]
