# Generated by Django 5.1.3 on 2025-02-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_lastknowndetails_last_seen_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='fir_no',
            new_name='fir_number',
        ),
        migrations.AlterField(
            model_name='fir',
            name='case_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Pending', 'Pending')], default='Open', max_length=50, null=True),
        ),
    ]
