# Generated by Django 5.1.3 on 2025-03-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0005_alter_match_match_with_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_with',
            field=models.CharField(blank=True, choices=[('Missing Person', 'Missing Person'), ('Unidentified Person', 'Unidentified Person'), ('Unidentified Body', 'Unidentified Body')], help_text='The type of the matched entity', max_length=20, null=True),
        ),
    ]
