# Generated by Django 5.1.3 on 2025-02-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0005_rename_fir_no_fir_fir_number_alter_fir_case_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='Mainapp_add_type_e00e8a_idx',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='type',
            new_name='address_type',
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address_type', 'city', 'state', 'pincode'], name='Mainapp_add_address_967e45_idx'),
        ),
    ]
