# Generated by Django 5.1.3 on 2025-03-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_alter_match_match_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_user_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('reporting', 'Reporting'), ('volunteer', 'Volunteer'), ('family', 'Family'), ('admin', 'Admin'), ('sub-admin', 'Sub-Admin'), ('officer', 'Officer'), ('police_station', 'Police Station'), ('hospital', 'Hospital'), ('developer', 'Developer')], default='reporting', max_length=20),
        ),
    ]
