# Generated by Django 5.1.3 on 2025-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_remove_address_mainapp_add_type_e00e8a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='social_media_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
