# Generated by Django 5.1.3 on 2025-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_contact_social_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='mother_tongue',
            field=models.CharField(blank=True, choices=[('hindi', 'Hindi'), ('english', 'English'), ('bengali', 'Bengali'), ('malayalam', 'Malayalam'), ('tamil', 'Tamil'), ('telegram', 'Telegram'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('sikh', 'Sikh'), ('cristian', 'Cristian')], max_length=50, null=True),
        ),
    ]
