# Generated by Django 5.1.3 on 2025-03-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_alter_user_sub_user_type_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('reporting', 'Reporting'), ('volunteer', 'Volunteer'), ('family', 'Family'), ('admin', 'Admin'), ('police_station', 'Police Station'), ('medical_staff', 'Medical_staff')], default='reporting', max_length=20),
        ),
    ]
