# Generated by Django 5.1.3 on 2025-02-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0008_alter_additionalinfo_mother_tongue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastknowndetails',
            name='missing_location_place',
        ),
    ]
