# Generated by Django 5.1.3 on 2025-02-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0008_alter_address_person_alter_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastknowndetails',
            name='person_photo',
            field=models.ImageField(blank=True, help_text='URL or Base64 encoded photo of the person', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lastknowndetails',
            name='reference_photo',
            field=models.ImageField(blank=True, help_text='URL or Base64 encoded reference photo', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_contact', to='Mainapp.contact'),
        ),
    ]
