# Generated by Django 5.1.3 on 2025-03-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0009_alter_user_is_staff_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
