# Generated by Django 5.1.3 on 2025-02-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0009_remove_lastknowndetails_missing_location_place'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='Mainapp_per_photo_u_816075_idx',
        ),
        migrations.RemoveField(
            model_name='person',
            name='photo_upload',
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['distinctive_mark', 'birth_mark', 'Body_Condition'], name='Mainapp_per_distinc_d88337_idx'),
        ),
    ]
