# Generated by Django 5.1.3 on 2025-03-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0010_remove_person_mainapp_per_photo_u_816075_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('PERMANENT', 'Permanent'), ('CURRENT', 'Current'), ('OLD', 'Old'), ('HOME', 'Home'), ('OFFICE', 'Office')], db_index=True, max_length=10, null=True),
        ),
    ]
