# Generated by Django 5.1.3 on 2025-03-13 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0010_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reported_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
