# Generated by Django 5.1.3 on 2025-03-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0012_user_password2'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='Mainapp_con_created_3b2e5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='Mainapp_con_updated_5e4798_idx',
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
