# Generated by Django 5.1.3 on 2025-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0012_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('United States of America', 'United States of America'), ('China', 'China'), ('Japan', 'Japan'), ('Germany', 'Germany'), ('United Kingdom', 'United Kingdom'), ('France', 'France'), ('Brazil', 'Brazil'), ('Australia', 'Australia'), ('Canada', 'Canada'), ('Russia', 'Russia'), ('Italy', 'Italy'), ('South Korea', 'South Korea'), ('Mexico', 'Mexico'), ('South Africa', 'South Africa'), ('Indonesia', 'Indonesia'), ('Saudi Arabia', 'Saudi Arabia'), ('Turkey', 'Turkey'), ('Spain', 'Spain'), ('Netherlands', 'Netherlands')], db_index=True, default='India', help_text='Country code or ID', max_length=50, null=True),
        ),
    ]
