# Generated by Django 5.1.3 on 2025-02-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0012_alter_lastknowndetails_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firs', to='Mainapp.person'),
        ),
    ]
