# Generated by Django 5.1.3 on 2025-03-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0013_remove_contact_mainapp_con_created_3b2e5d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastknowndetails',
            name='missing_date',
            field=models.DateTimeField(blank=True, help_text='Date the person went missing', null=True),
        ),
        migrations.AlterField(
            model_name='lastknowndetails',
            name='missing_time',
            field=models.DateTimeField(blank=True, help_text='Exact time the person was last seen', null=True),
        ),
    ]
