# Generated by Django 5.1.3 on 2025-03-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0013_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='id_no',
            field=models.CharField(help_text='Unique identification number', max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhar', 'Aadhar'), ('pan', 'PAN'), ('dl', 'Driving License'), ('passport', 'Passport')], max_length=100, null=True),
        ),
    ]
