# Generated by Django 5.1.3 on 2025-03-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0014_alter_lastknowndetails_missing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastknowndetails',
            name='missing_time',
            field=models.TimeField(blank=True, help_text='Exact time the person was last seen', null=True),
        ),
    ]
