# Generated by Django 5.1.3 on 2025-03-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0014_alter_person_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='station_photo',
            field=models.ImageField(blank=True, null=True, upload_to='police_station_photos/'),
        ),
    ]
