# Generated by Django 5.1.3 on 2025-03-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0014_alter_additionalinfo_id_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='lastknowndetails',
            name='person_photo',
            field=models.ImageField(blank=True, help_text='URL or Base64 encoded photo of the person', null=True, upload_to='All_Photos'),
        ),
        migrations.AlterField(
            model_name='lastknowndetails',
            name='reference_photo',
            field=models.ImageField(blank=True, help_text='URL or Base64 encoded reference photo', null=True, upload_to='All_Photos'),
        ),
    ]
