# Generated by Django 5.1.3 on 2025-02-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0015_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('Missing Person', 'Missing Person'), ('Unidentifed Person', 'Unidentifed Person'), ('Unidentified Body', 'Unidentified Body')], max_length=20),
        ),
    ]
