# Generated by Django 5.1.3 on 2025-03-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0015_alter_lastknowndetails_missing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastknowndetails',
            name='missing_time',
        ),
    ]
