# Generated by Django 5.1.3 on 2025-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0015_policestation_station_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='activ_Status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True),
        ),
    ]
