# Generated by Django 5.1.3 on 2025-03-05 07:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0016_address_person_type_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address_type',
            field=models.CharField(blank=True, choices=[('PERMANENT', 'Permanent'), ('CURRENT', 'Current'), ('OLD', 'Old'), ('HOME', 'Home'), ('OFFICE', 'Office')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='appartment_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='appartment_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('United States of America', 'United States of America'), ('China', 'China'), ('Japan', 'Japan'), ('Germany', 'Germany'), ('United Kingdom', 'United Kingdom'), ('France', 'France'), ('Brazil', 'Brazil'), ('Australia', 'Australia'), ('Canada', 'Canada'), ('Russia', 'Russia'), ('Italy', 'Italy'), ('South Korea', 'South Korea'), ('Mexico', 'Mexico'), ('South Africa', 'South Africa'), ('Indonesia', 'Indonesia'), ('Saudi Arabia', 'Saudi Arabia'), ('Turkey', 'Turkey'), ('Spain', 'Spain'), ('Netherlands', 'Netherlands')], db_index=True, default='India', help_text='Country code or ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='landmark_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(blank=True, choices=[('Missing person', 'Missing person'), ('Unidentified person', 'Unidentified person'), ('Unidentified body', 'Unidentified body')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='village',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
