# Generated by Django 5.1.3 on 2025-03-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0016_remove_lastknowndetails_missing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastknowndetails',
            name='missing_time',
            field=models.TimeField(blank=True, help_text='Exact time the person was last seen', null=True),
        ),
        migrations.AlterField(
            model_name='lastknowndetails',
            name='missing_date',
            field=models.DateField(blank=True, help_text='Date the person went missing', null=True),
        ),
    ]
