# Generated by Django 5.1.3 on 2025-03-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0016_policestation_activ_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Hospitals_photos/'),
        ),
    ]
