# Generated by Django 5.1.3 on 2025-03-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0017_lastknowndetails_missing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], db_index=True, max_length=5, null=True),
        ),
    ]
