# Generated by Django 5.1.3 on 2025-03-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0017_person_address_type_person_appartment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_type',
        ),
    ]
