# Generated by Django 5.1.3 on 2025-02-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0017_remove_address_police_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent', to='Mainapp.person'),
        ),
    ]
