# Generated by Django 5.1.3 on 2025-03-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0018_remove_person_person_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='person_type',
        ),
    ]
