# Generated by Django 5.1.3 on 2025-02-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0018_consent_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='is_consent',
            field=models.BooleanField(default=False),
        ),
    ]
