# Generated by Django 5.1.3 on 2025-02-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0019_consent_is_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_contact', to='Mainapp.policestation'),
        ),
    ]
