# Generated by Django 5.1.3 on 2025-03-06 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0019_remove_address_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='case_status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='date_reported',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='person',
            name='match_entity_id',
            field=models.UUIDField(blank=True, help_text='ID of the matched entity (Missing/Unidentified Person/Body)', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='match_type',
            field=models.CharField(blank=True, choices=[('Missing Person', 'Missing Person'), ('Unidentified Person', 'Unidentified Person'), ('Unidentified Body', 'Unidentified Body')], help_text='The type of the matched entity', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['match_entity_id', 'match_type'], name='Mainapp_per_match_e_dc879c_idx'),
        ),
    ]
