# Generated by Django 5.1.3 on 2025-03-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0020_person_case_status_person_date_reported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='case_status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Pending', 'Pending')], db_index=True, default='Pending', max_length=10),
        ),
    ]
