# Generated by Django 5.1.3 on 2025-02-24 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0020_alter_contact_police_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_contact', to='Mainapp.hospital'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.address'),
        ),
    ]
