# Generated by Django 5.1.3 on 2025-02-25 06:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0021_remove_hospital_address_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='address',
            name='lat',
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
