# Generated by Django 5.1.3 on 2025-03-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0021_alter_person_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='case_status',
            field=models.CharField(choices=[('Resolved', 'resolved'), ('Pending', 'pending')], db_index=True, default='pending', max_length=10),
        ),
    ]
