# Generated by Django 5.1.3 on 2025-02-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0022_remove_address_lang_remove_address_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_user_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('reporting', 'Reporting'), ('volunteer', 'Volunteer'), ('family', 'Family'), ('admin', 'Admin'), ('sub-admin', 'Sub-Admin'), ('officer', 'Officer'), ('police_station', 'Police Station'), ('hospital', 'Hospital')], default='reporting', max_length=20),
        ),
    ]
