# Generated by Django 5.1.3 on 2025-03-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0022_alter_person_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_photo',
            field=models.ImageField(blank=True, help_text='URL or Base64 encoded photo of the person', null=True, upload_to='All_Photos'),
        ),
    ]
