# Generated by Django 5.1.3 on 2025-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0023_person_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('Missing Person', 'Missing Person'), ('Unidentified Person', 'Unidentified Person'), ('Unidentified Body', 'Unidentified Body')], db_index=True, max_length=20),
        ),
    ]
