# Generated by Django 5.1.3 on 2025-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0023_user_sub_user_type_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('reporting', 'Reporting'), ('volunteer', 'Volunteer'), ('family', 'Family'), ('admin', 'Admin'), ('sub-admin', 'Sub-Admin'), ('officer', 'Officer'), ('police_station', 'Police Station'), ('hospital', 'Hospital'), ('Developer', 'Developer')], default='reporting', max_length=20),
        ),
    ]
