# Generated by Django 5.1.3 on 2025-03-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0024_alter_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], db_index=True, max_length=5, null=True),
        ),
    ]
