# Generated by Django 5.1.3 on 2025-02-25 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0024_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mainapp.consent'),
        ),
    ]
