# Generated by Django 5.1.3 on 2025-02-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0027_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_mark_details',
        ),
    ]
