# Generated by Django 5.1.3 on 2025-02-26 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0031_alter_contact_created_at_alter_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='caste',
            field=models.CharField(blank=True, choices=[('sc', 'Scheduled Caste (SC)'), ('st', 'Scheduled Tribe (ST)'), ('obc', 'Other Backward Class (OBC)'), ('open', 'Open/General')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhar', 'Aadhar'), ('pan', 'PAN'), ('dl', 'Driving License'), ('passport', 'Passport')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consent',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consent',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, choices=[('fir', 'FIR'), ('id', 'ID'), ('dna_report', 'DNA Report'), ('postmortem_report', 'Postmortem Report'), ('fingerprint_report', 'Fingerprint Report')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='case_status',
            field=models.CharField(blank=True, help_text='Current status of the case', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='fir_no',
            field=models.CharField(blank=True, help_text='Unique FIR number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='investigation_officer_name',
            field=models.CharField(blank=True, help_text='Name of the investigation officer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lastknowndetails',
            name='missing_date',
            field=models.DateTimeField(blank=True, help_text='Date the person went missing', null=True),
        ),
        migrations.AlterField(
            model_name='lastknowndetails',
            name='missing_time',
            field=models.DateTimeField(blank=True, help_text='Exact time the person was last seen', null=True),
        ),
    ]
