# Generated by Django 5.1.3 on 2025-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0033_alter_additionalinfo_user_alter_person_birthtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
