# Generated by Django 5.1.3 on 2025-02-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0034_alter_person_birthtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
