# Generated by Django 5.1.3 on 2025-02-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0035_alter_person_birthtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthtime',
        ),
    ]
