# Generated by Django 5.1.3 on 2025-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0036_remove_person_birthtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
