# Generated by Django 5.1.3 on 2025-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0037_person_birthtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastknowndetails',
            name='missing_time',
            field=models.TimeField(blank=True, help_text='Exact time the person was last seen', null=True),
        ),
    ]
