# Generated by Django 5.1.3 on 2025-02-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0038_alter_lastknowndetails_missing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.document'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.policestation'),
        ),
    ]
