# Generated by Django 5.1.3 on 2025-02-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0039_alter_fir_document_alter_fir_police_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='id_no',
            field=models.CharField(help_text='Unique identification number', max_length=50),
        ),
    ]
