# Generated by Django 5.1.3 on 2025-02-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0040_alter_additionalinfo_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='fir_no',
            field=models.CharField(blank=True, help_text='Unique FIR number', max_length=50, null=True),
        ),
    ]
