# Generated by Django 5.1.3 on 2024-11-08 06:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_known_location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('date_missing', models.DateField()),
            ],
        ),
    ]
