# Generated by Django 5.1.3 on 2024-11-11 09:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='last_known_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
