# Generated by Django 5.1.3 on 2025-02-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_alter_person_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_by',
        ),
    ]
