# Generated by Django 5.1.3 on 2025-02-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_alter_address_created_by_alter_address_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='dob',
            new_name='birth_date',
        ),
    ]
