# Generated by Django 5.1.3 on 2025-02-21 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0009_alter_lastknowndetails_person_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mainapp.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('m', 'Missing'), ('up', 'Unidentifed Person'), ('ub', 'Unidentified Body')], max_length=2),
        ),
    ]
