# Generated by Django 5.1.3 on 2025-02-21 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0010_additionalinfo_person_alter_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_info', to='Mainapp.person'),
        ),
    ]
