# Generated by Django 5.1.3 on 2025-02-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0011_alter_additionalinfo_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastknowndetails',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_known_details', to='Mainapp.person'),
        ),
    ]
