# Generated by Django 5.1.3 on 2025-02-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0013_fir_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='_is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
