# Generated by Django 5.1.3 on 2025-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0014_person__is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='All_Photos/persons_photos/'),
        ),
    ]
