# Generated by Django 5.1.3 on 2025-02-21 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0016_alter_person_gender_alter_person_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='police_station',
        ),
        migrations.AlterField(
            model_name='policestation',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to='Mainapp.address'),
        ),
    ]
